name: green_city
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^14.8.1
  lottie: ^3.3.1
  google_nav_bar: ^5.0.7
  expandable: ^5.0.1
  image_picker: ^1.1.2
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^8.0.3
  modal_progress_hud_nsn: ^0.5.1
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.5.2
  percent_indicator: ^4.2.4
  flutter_launcher_icons: ^0.14.3
  rename: ^3.0.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  google_generative_ai: ^0.4.6
  flutter_bloc: ^9.1.0
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  flutter_native_splash: ^2.4.6
  flutter_localizations:
    sdk: flutter
  fl_chart: ^1.0.0
  intl: ^0.20.2
  flutter_chat_ui: ^1.6.8
  flutter_chat_types: ^3.6.2
  uuid: ^4.5.1
  dio: ^5.8.0+1
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.7.0
  webview_flutter_wkwebview: ^3.22.0
  app_links: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
flutter_intl:
  enabled: true

flutter_native_splash:
  color: "#000000" # Dark background (black)
  image: assets/images/logo.png

  android_12:
    image: assets/images/icon.png
    color: "#000000" # Dark background for Android 12 and above

  android: true
  ios: true
  web: true
